# Generated by Django 4.1.5 on 2023-01-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaLianFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bourse_name', models.CharField(max_length=255, verbose_name='交易所名称')),
                ('code', models.CharField(max_length=255, verbose_name='代码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('newest_price', models.CharField(max_length=255, verbose_name='最新价')),
                ('amount_increase_price', models.CharField(max_length=255, verbose_name='涨跌额')),
                ('amount_increase', models.CharField(max_length=255, verbose_name='涨跌幅')),
                ('opening_price', models.CharField(max_length=255, verbose_name='开盘价')),
                ('top_price', models.CharField(max_length=255, verbose_name='最高价')),
                ('bottom_price', models.CharField(max_length=255, verbose_name='最低价')),
                ('yesterday_price', models.CharField(max_length=255, verbose_name='昨收价')),
                ('update_time', models.CharField(max_length=255, verbose_name='更新时间')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='插入对象的时间')),
            ],
            options={
                'verbose_name': '大连期货交易所',
                'verbose_name_plural': '大连期货交易所',
                'db_table': 'dalian_futures_table',
            },
        ),
        migrations.CreateModel(
            name='ShangHaiFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bourse_name', models.CharField(max_length=255, verbose_name='交易所名称')),
                ('code', models.CharField(max_length=255, verbose_name='代码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('newest_price', models.CharField(max_length=255, verbose_name='最新价')),
                ('amount_increase_price', models.CharField(max_length=255, verbose_name='涨跌额')),
                ('amount_increase', models.CharField(max_length=255, verbose_name='涨跌幅')),
                ('opening_price', models.CharField(max_length=255, verbose_name='开盘价')),
                ('top_price', models.CharField(max_length=255, verbose_name='最高价')),
                ('bottom_price', models.CharField(max_length=255, verbose_name='最低价')),
                ('yesterday_price', models.CharField(max_length=255, verbose_name='昨收价')),
                ('update_time', models.CharField(max_length=255, verbose_name='更新时间')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='插入对象的时间')),
            ],
            options={
                'verbose_name': '上海期货交易所',
                'verbose_name_plural': '上海期货交易所',
                'db_table': 'shanghai_futures_table',
            },
        ),
        migrations.CreateModel(
            name='ZhengZhouFutures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bourse_name', models.CharField(max_length=255, verbose_name='交易所名称')),
                ('code', models.CharField(max_length=255, verbose_name='代码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('newest_price', models.CharField(max_length=255, verbose_name='最新价')),
                ('amount_increase_price', models.CharField(max_length=255, verbose_name='涨跌额')),
                ('amount_increase', models.CharField(max_length=255, verbose_name='涨跌幅')),
                ('opening_price', models.CharField(max_length=255, verbose_name='开盘价')),
                ('top_price', models.CharField(max_length=255, verbose_name='最高价')),
                ('bottom_price', models.CharField(max_length=255, verbose_name='最低价')),
                ('yesterday_price', models.CharField(max_length=255, verbose_name='昨收价')),
                ('update_time', models.CharField(max_length=255, verbose_name='更新时间')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='插入对象的时间')),
            ],
            options={
                'verbose_name': '郑州期货交易所',
                'verbose_name_plural': '郑州期货交易所',
                'db_table': 'zhengzhou_futures_table',
            },
        ),
    ]
